# Generated by Django 6.0.3 on 2026-03-10 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('subject', models.CharField(max_length=160)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=180)),
                ('venue', models.CharField(max_length=180)),
                ('event_date', models.DateField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('planning', 'Planning'), ('confirmed', 'Confirmed'), ('completed', 'Completed')], default='open', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('event_date', 'display_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=160)),
                ('category', models.CharField(max_length=80)),
                ('description', models.TextField(blank=True)),
                ('image_url', models.CharField(max_length=255)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('display_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('eyebrow', models.CharField(blank=True, max_length=120)),
                ('title', models.CharField(max_length=255)),
                ('short_title', models.CharField(blank=True, max_length=120)),
                ('description', models.TextField(blank=True)),
                ('feature', models.CharField(blank=True, max_length=255)),
                ('image_url', models.CharField(max_length=255)),
                ('credit', models.CharField(blank=True, max_length=255)),
                ('primary_label', models.CharField(blank=True, max_length=80)),
                ('primary_href', models.CharField(blank=True, max_length=160)),
                ('secondary_label', models.CharField(blank=True, max_length=80)),
                ('secondary_href', models.CharField(blank=True, max_length=160)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('display_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='MemberProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('category', models.CharField(choices=[('president', 'President'), ('vice_president', 'Vice-President'), ('secretariat', 'Secretariat'), ('advisory', 'Advisory'), ('member', 'Member')], max_length=32)),
                ('role', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('photo_url', models.CharField(blank=True, max_length=255)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('display_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ServiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tag', models.CharField(max_length=80)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('points', models.JSONField(blank=True, default=list)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('display_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization_name', models.CharField(default='Khichapokhari Newroad Business Association', max_length=255)),
                ('short_name', models.CharField(default='KNBA', max_length=50)),
                ('office_address', models.CharField(default='Khichapokhari, New Road, Kathmandu', max_length=255)),
                ('office_phone', models.CharField(default='+977-1-5350000', max_length=50)),
                ('office_email', models.EmailField(default='secretariat@knba.org.np', max_length=254)),
                ('emergency_label', models.CharField(default='Emergency Notice', max_length=120)),
                ('emergency_message', models.TextField(default='For urgent market coordination, safety concerns, or service disruption updates, contact the KNBA secretariat immediately.')),
                ('emergency_contact', models.CharField(default='+977-1-5350000', max_length=50)),
                ('history_text', models.TextField(blank=True)),
                ('founder_name', models.CharField(blank=True, max_length=120)),
                ('founder_title', models.CharField(blank=True, max_length=120)),
                ('founder_message', models.TextField(blank=True)),
                ('founder_image_url', models.CharField(blank=True, max_length=255)),
                ('president_name', models.CharField(blank=True, max_length=120)),
                ('president_title', models.CharField(blank=True, max_length=120)),
                ('president_message', models.TextField(blank=True)),
                ('president_image_url', models.CharField(blank=True, max_length=255)),
                ('mission_text', models.TextField(blank=True)),
                ('vision_text', models.TextField(blank=True)),
                ('map_embed_url', models.TextField(blank=True)),
                ('social_links', models.JSONField(blank=True, default=list)),
            ],
            options={
                'verbose_name_plural': 'Site settings',
            },
        ),
    ]
