# Generated by Django 6.0.3 on 2026-03-12 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization_name', models.CharField(default='Khichapokhari Newroad Business Association', max_length=255)),
                ('short_name', models.CharField(default='KNBA', max_length=50)),
                ('registration_number', models.CharField(blank=True, max_length=120)),
                ('established_year', models.CharField(blank=True, max_length=20)),
                ('tagline', models.CharField(blank=True, max_length=255)),
                ('office_address', models.CharField(default='Khichapokhari, New Road, Kathmandu', max_length=255)),
                ('area', models.CharField(blank=True, max_length=120)),
                ('city', models.CharField(default='Kathmandu', max_length=120)),
                ('district', models.CharField(blank=True, max_length=120)),
                ('province', models.CharField(blank=True, max_length=120)),
                ('country', models.CharField(default='Nepal', max_length=120)),
                ('postal_code', models.CharField(blank=True, max_length=30)),
                ('primary_phone', models.CharField(default='+977-1-5350000', max_length=50)),
                ('secondary_phone', models.CharField(blank=True, max_length=50)),
                ('primary_email', models.EmailField(default='secretariat@knba.org.np', max_length=254)),
                ('secondary_email', models.EmailField(blank=True, max_length=254)),
                ('website_url', models.URLField(blank=True)),
                ('map_embed_url', models.TextField(blank=True)),
                ('logo_url', models.CharField(blank=True, max_length=255)),
                ('about_summary', models.TextField(blank=True)),
                ('mission_summary', models.TextField(blank=True)),
                ('vision_summary', models.TextField(blank=True)),
                ('social_links', models.JSONField(blank=True, default=list)),
            ],
            options={
                'verbose_name': 'Organization profile',
                'verbose_name_plural': 'Organization profile',
            },
        ),
    ]
