# Generated by Django 6.0.3 on 2026-03-12 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_organizationprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organizationprofile',
            options={'ordering': ('-is_active', '-updated_at', 'organization_name', 'id'), 'verbose_name': 'Organization profile', 'verbose_name_plural': 'Organization profile'},
        ),
        migrations.RemoveField(
            model_name='organizationprofile',
            name='about_summary',
        ),
        migrations.RemoveField(
            model_name='organizationprofile',
            name='area',
        ),
        migrations.RemoveField(
            model_name='organizationprofile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='organizationprofile',
            name='country',
        ),
        migrations.RemoveField(
            model_name='organizationprofile',
            name='district',
        ),
        migrations.RemoveField(
            model_name='organizationprofile',
            name='established_year',
        ),
        migrations.RemoveField(
            model_name='organizationprofile',
            name='logo_url',
        ),
        migrations.RemoveField(
            model_name='organizationprofile',
            name='mission_summary',
        ),
        migrations.RemoveField(
            model_name='organizationprofile',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='organizationprofile',
            name='primary_email',
        ),
        migrations.RemoveField(
            model_name='organizationprofile',
            name='primary_phone',
        ),
        migrations.RemoveField(
            model_name='organizationprofile',
            name='province',
        ),
        migrations.RemoveField(
            model_name='organizationprofile',
            name='registration_number',
        ),
        migrations.RemoveField(
            model_name='organizationprofile',
            name='secondary_email',
        ),
        migrations.RemoveField(
            model_name='organizationprofile',
            name='secondary_phone',
        ),
        migrations.RemoveField(
            model_name='organizationprofile',
            name='social_links',
        ),
        migrations.RemoveField(
            model_name='organizationprofile',
            name='tagline',
        ),
        migrations.RemoveField(
            model_name='organizationprofile',
            name='vision_summary',
        ),
        migrations.RemoveField(
            model_name='organizationprofile',
            name='website_url',
        ),
        migrations.AddField(
            model_name='organizationprofile',
            name='email',
            field=models.EmailField(default='secretariat@knba.org.np', max_length=254),
        ),
        migrations.AddField(
            model_name='organizationprofile',
            name='favicon_icon',
            field=models.ImageField(blank=True, null=True, upload_to='organization/favicons/'),
        ),
        migrations.AddField(
            model_name='organizationprofile',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organizationprofile',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='organization/logos/'),
        ),
        migrations.AddField(
            model_name='organizationprofile',
            name='phone_number',
            field=models.CharField(default='+977-1-5350000', max_length=50),
        ),
    ]
