# Generated by Django 6.0.3 on 2026-03-12 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_organizationprofile_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationprofile',
            name='favicon_icon',
        ),
    ]
