# Generated by Django 6.0.3 on 2026-03-13 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_businessshowcaseitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberprofile',
            name='note',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='members/photos/'),
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='category',
            field=models.CharField(choices=[('leadership', 'Leadership'), ('executive', 'Executive Committee'), ('advisory', 'Advisory Panel')], max_length=32),
        ),
    ]
