# Generated by Django 6.0.3 on 2026-03-13 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_memberprofile_note_memberprofile_photo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommitteeTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(blank=True, max_length=120)),
                ('start_year', models.PositiveSmallIntegerField()),
                ('end_year', models.PositiveSmallIntegerField()),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_current', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('-is_current', 'display_order', '-start_year', 'id'),
            },
        ),
        migrations.AlterModelOptions(
            name='memberprofile',
            options={'ordering': ('term__display_order', 'display_order', 'id')},
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='api.committeeterm'),
        ),
    ]
