# Generated by Django 6.0.3 on 2026-03-13 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_committeeterm_alter_memberprofile_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessShowcaseSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitter_name', models.CharField(max_length=120)),
                ('submitter_email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=180)),
                ('category', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('phone', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='business-showcase/submissions/')),
                ('image_url', models.CharField(blank=True, max_length=255)),
                ('badge', models.CharField(default='Business Showcase', max_length=80)),
                ('website_url', models.URLField(blank=True)),
                ('facebook_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('ecommerce_url', models.URLField(blank=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('review_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('published_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_submissions', to='api.businessshowcaseitem')),
            ],
            options={
                'ordering': ('-created_at', 'id'),
            },
        ),
    ]
