# Generated by Django 6.0.3 on 2026-03-13 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_businessshowcasesubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessshowcasesubmission',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
