# Generated by Django 6.0.3 on 2026-03-16 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_businessshowcasesubmission_is_read'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(default='Emergency Notice', max_length=120)),
                ('message', models.TextField(default='For urgent market coordination, safety concerns, or service disruption updates, contact the KNBA secretariat immediately.')),
                ('button_label', models.CharField(default='View Notice', max_length=80)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='emergency-notices/pdfs/')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('-is_active', '-updated_at', '-created_at', '-id'),
            },
        ),
    ]
