# Generated by Django 6.0.3 on 2026-03-22 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_emergencynotice'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_name', models.CharField(max_length=180)),
                ('contact_person', models.CharField(max_length=120)),
                ('category', models.CharField(blank=True, max_length=120)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('office_address', models.CharField(blank=True, max_length=255)),
                ('joined_date', models.DateField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('business_name', 'contact_person', 'id'),
            },
        ),
    ]
