# Generated by Django 6.0.3 on 2026-03-24 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_contactreply'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactreply',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='contact-replies/attachments/'),
        ),
    ]
