# Generated by Django 6.0.3 on 2026-06-10 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_contactreply_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='home_about_eyebrow',
            field=models.CharField(default='About KNBA', max_length=120),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='home_about_title',
            field=models.CharField(default='KNBA builds a unified business voice for Khichapokhari and New Road.', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='home_business_description',
            field=models.TextField(default='This sponsored directory gives member businesses a stronger public presence while creating a practical fundraising stream for the association.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='home_business_eyebrow',
            field=models.CharField(default='Business Showcase', max_length=120),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='home_business_title',
            field=models.CharField(default='Promoted businesses that help support KNBA operations.', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='home_gallery_description',
            field=models.TextField(default='A snapshot of KNBA activities across meetings, celebrations, training sessions, and collaboration on New Road.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='home_gallery_eyebrow',
            field=models.CharField(default='Gallery', max_length=120),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='home_gallery_title',
            field=models.CharField(default='Moments from events, market coordination, and member programs.', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='home_services_description',
            field=models.TextField(default='These service cards now come from the live KNBA service records managed in the portal.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='home_services_eyebrow',
            field=models.CharField(default='Core Services', max_length=120),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='home_services_title',
            field=models.CharField(default='Practical support that makes day-to-day business easier.', max_length=255),
        ),
    ]
