# Generated by Django 6.0.3 on 2026-06-10 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_widen_business_showcase_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='calendar_pdf',
            field=models.FileField(blank=True, null=True, upload_to='about/calendar/'),
        ),
    ]
