# Generated by Django 6.0.3 on 2026-06-10 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_sitesettings_calendar_pdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galleryitem',
            name='show_in_slider',
        ),
    ]
